name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow pushing
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: KrispNut
          outputs: github-contribution-grid-snake.svg   # 👈 direct output here

      - name: Push to output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B output
          git add github-contribution-grid-snake.svg
          git commit -m "Generated contribution snake" || echo "No changes to commit"
          git push origin output --force
